# Generated by Django 5.2.4 on 2025-07-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video'),
        ('instructors', '0004_remove_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkedcourse',
            name='course_id',
        ),
        migrations.AddField(
            model_name='bookmarkedcourse',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.video'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
