# Generated by Django 5.2.4 on 2025-07-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bookmarkedcourse_course_id_and_more'),
        ('instructors', '0004_remove_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkedcourse',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.video'),
        ),
    ]
