# Generated by Django 5.2.4 on 2025-07-07 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('instructors', 'Category')
    default_categories = [
        'Basic Computer',
        'Agro-based',
        'Social media',
        'Handicraft',
        'Design',
        'Business',
        'Marketing',
    ]
    for cat in default_categories:
        Category.objects.get_or_create(name=cat)

class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructors.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_no', models.PositiveIntegerField()),
                ('video', models.FileField(upload_to='lesson_videos/')),
                ('pdf_notes', models.FileField(blank=True, null=True, upload_to='lesson_pdfs/')),
                ('assignment_description', models.TextField(blank=True)),
                ('assignment_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='instructors.course')),
            ],
            options={
                'ordering': ['lesson_no'],
                'unique_together': {('course', 'lesson_no')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='instructors.lesson')),
            ],
        ),
        migrations.RunPython(
            code=create_default_categories,
            reverse_code=migrations.RunPython.noop,
        ),
    ]