# Generated by Django 5.2.4 on 2025-07-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_category_course_lesson_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('basic-computer', 'Basic Computer'), ('agro-based', 'Agro-based'), ('social-media', 'Social Media'), ('handicrafts', 'Handicrafts'), ('design', 'Design'), ('business', 'Business'), ('marketing', 'Marketing')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
