# Generated by Django 5.2.4 on 2025-07-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_quicklink_remove_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
    ]
