# Generated by Django 5.2.4 on 2025-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_remove_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='assignment_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='pdf_notes',
            field=models.FileField(blank=True, null=True, upload_to='video_pdfs/'),
        ),
    ]
