# Generated by Django 5.2.4 on 2025-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('agro-based', 'Agro-based'), ('handicraft', 'Handicraft'), ('basic computer', 'Basic computer'), ('design', 'Design & Fashion'), ('business', 'Business'), ('marketing', 'Marketing'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(default=3, upload_to='course_videos/'),
            preserve_default=False,
        ),
    ]
